all: Node.h InternalNode.h TerminalNode.h HuffmanTree.h Node.cpp InternalNode.cpp TerminalNode.cpp HuffmanTree.cpp main.cpp
	g++ Node.cpp InternalNode.cpp TerminalNode.cpp HuffmanTree.cpp main.cpp -o w6
clean:
	rm -f *.o
	rm -f *.out
	rm -f w6
